# Generated by Django 6.0.6 on 2026-06-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(choices=[('disabled', 'Disabled'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='disabled', max_length=16)),
                ('schedule_time', models.TimeField(default='02:00', help_text='Time of day (server local) to run')),
                ('schedule_day', models.IntegerField(blank=True, help_text='Weekly: 0=Mon..6=Sun. Monthly: 1-28. Ignored for daily.', null=True)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('include_postgres', models.BooleanField(default=True)),
                ('include_influxdb', models.BooleanField(default=False)),
                ('include_openbao', models.BooleanField(default=True)),
                ('include_config_files', models.BooleanField(default=True)),
                ('include_ssl_certs', models.BooleanField(default=True)),
                ('include_influxdb_days', models.PositiveIntegerField(default=30)),
                ('local_path', models.CharField(default='/opt/spane/backups', max_length=512)),
                ('destination', models.CharField(choices=[('local', 'Local filesystem'), ('scp', 'SCP / SFTP'), ('git', 'Git repository'), ('s3', 'S3 / object storage')], default='local', max_length=8)),
                ('scp_host', models.CharField(blank=True, max_length=255)),
                ('scp_port', models.IntegerField(default=22)),
                ('scp_username', models.CharField(blank=True, max_length=128)),
                ('scp_path', models.CharField(blank=True, max_length=512)),
                ('git_repo_url', models.CharField(blank=True, max_length=512)),
                ('git_branch', models.CharField(default='main', max_length=128)),
                ('git_path', models.CharField(default='spane/', max_length=256)),
                ('s3_bucket', models.CharField(blank=True, max_length=255)),
                ('s3_prefix', models.CharField(default='spane-backups/', max_length=256)),
                ('s3_endpoint', models.CharField(blank=True, max_length=255)),
                ('s3_region', models.CharField(default='us-east-1', max_length=64)),
                ('encryption_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backup Configuration',
                'verbose_name_plural': 'Backup Configuration',
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='running', max_length=10)),
                ('triggered_by', models.CharField(default='scheduled', max_length=32)),
                ('components', models.JSONField(default=dict)),
                ('filename', models.CharField(blank=True, max_length=512)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('local_path', models.CharField(blank=True, max_length=1024)),
                ('remote_path', models.CharField(blank=True, max_length=1024)),
                ('error_message', models.TextField(blank=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('encrypted', models.BooleanField(default=False)),
                ('encryption_hint', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
