server_name: edgebad
listen: 0.0.0.0:4222
http:   0.0.0.0:8222
jetstream { domain: edgebad, store_dir: "/data/js" }
leafnodes {
  remotes: [
    {
      url: "tls://leafproxy:7422"
      credentials: "/creds/COLL1.creds"
      tls {
        cert_file: "/certs/edgebad-cert.pem"
        key_file:  "/certs/edgebad-key.pem"
        ca_file:   "/certs/ca.pem"
        min_version: "1.3"
        handshake_first: true
      }
    }
  ]
}
