# Generated by Django 6.0.5 on 2026-06-03 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0017_discovereddevice_device_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MACVendor',
            fields=[
                ('oui', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('vendor', models.CharField(max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ARPEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=17)),
                ('interface', models.CharField(blank=True, max_length=64)),
                ('vlan', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(default='Internet', max_length=20)),
                ('age_minutes', models.IntegerField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arp_entries', to='devices.device')),
            ],
            options={
                'indexes': [models.Index(fields=['mac_address'], name='arp_mac_arp_mac_add_b4ef60_idx'), models.Index(fields=['ip_address'], name='arp_mac_arp_ip_addr_dddeb5_idx'), models.Index(fields=['device', 'collected_at'], name='arp_mac_arp_device__3f405b_idx')],
                'unique_together': {('device', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='MACEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17)),
                ('vlan', models.IntegerField(blank=True, null=True)),
                ('interface', models.CharField(blank=True, max_length=64)),
                ('entry_type', models.CharField(default='dynamic', max_length=20)),
                ('collected_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mac_entries', to='devices.device')),
            ],
            options={
                'indexes': [models.Index(fields=['mac_address'], name='arp_mac_mac_mac_add_cda787_idx'), models.Index(fields=['device', 'vlan'], name='arp_mac_mac_device__c2f103_idx'), models.Index(fields=['collected_at'], name='arp_mac_mac_collect_7fbdd9_idx')],
                'unique_together': {('device', 'mac_address', 'vlan')},
            },
        ),
    ]
