# Generated by Django 6.0.5 on 2026-06-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arp_mac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arpentry',
            name='entry_type',
            field=models.CharField(blank=True, default='dynamic', max_length=20),
        ),
    ]
