# Generated by Django 6.0.5 on 2026-05-30 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10)),
                ('log_default_time_range', models.CharField(choices=[('15m', 'Last 15 minutes'), ('1h', 'Last 1 hour'), ('4h', 'Last 4 hours'), ('12h', 'Last 12 hours'), ('24h', 'Last 24 hours'), ('7d', 'Last 7 days'), ('all', 'All time')], default='1h', max_length=4)),
                ('log_default_page_size', models.IntegerField(default=50)),
                ('log_auto_refresh', models.BooleanField(default=False)),
                ('devices_default_columns', models.JSONField(blank=True, default=list)),
                ('devices_page_size', models.IntegerField(default=25)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('date_format', models.CharField(choices=[('iso', '2026-05-30'), ('us', '05/30/2026'), ('eu', '30/05/2026')], default='iso', max_length=4)),
                ('email_alerts', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user preferences',
                'verbose_name_plural': 'user preferences',
            },
        ),
    ]
