# Generated by Django 6.0.5 on 2026-06-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='discord_user_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='slack_user_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
