# Generated by Django 6.0.6 on 2026-06-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userpreferences_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='netpulseuser',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
