# Generated by Django 6.0.6 on 2026-06-08 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_netpulseuser_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_role_changed', 'User Role Changed'), ('device_created', 'Device Created'), ('device_updated', 'Device Updated'), ('device_deleted', 'Device Deleted'), ('device_approved', 'Device Approved'), ('device_rejected', 'Device Rejected'), ('config_pushed', 'Config Pushed to Device'), ('config_backup', 'Config Backup Taken'), ('config_restored', 'Config Restored'), ('compliance_run', 'Compliance Check Run'), ('credential_created', 'Credential Created'), ('credential_updated', 'Credential Updated'), ('credential_deleted', 'Credential Deleted'), ('credential_accessed', 'Credential Accessed'), ('discovery_started', 'Discovery Started'), ('discovery_completed', 'Discovery Completed'), ('netbox_import', 'NetBox Import'), ('unifi_sync', 'UniFi Sync'), ('settings_changed', 'Settings Changed'), ('api_key_created', 'API Key Created'), ('api_key_deleted', 'API Key Deleted'), ('sso_config_changed', 'SSO Config Changed'), ('alert_acknowledged', 'Alert Acknowledged'), ('alert_resolved', 'Alert Resolved'), ('alert_rule_created', 'Alert Rule Created'), ('alert_rule_updated', 'Alert Rule Updated')], db_index=True, max_length=64)),
                ('username', models.CharField(blank=True, help_text='Snapshot of the username at event time.', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('target_type', models.CharField(blank=True, db_index=True, help_text='e.g. Device, User, Credential', max_length=64)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('target_name', models.CharField(blank=True, help_text="Snapshot of the target's name.", max_length=256)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('error_message', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='core_auditl_event_t_dff433_idx'), models.Index(fields=['user', '-created_at'], name='core_auditl_user_id_969660_idx'), models.Index(fields=['target_type', 'target_id'], name='core_auditl_target__6c66b3_idx')],
            },
        ),
    ]
