# Generated by Django 6.0.6 on 2026-06-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_auditlog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='temperature_unit',
            field=models.CharField(choices=[('C', 'Celsius (°C)'), ('F', 'Fahrenheit (°F)')], default='C', max_length=1),
        ),
    ]
