# Generated by Django 6.0.6 on 2026-06-20 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_auditlog_event_type'),
        ('core', '0011_auditlog_chatops_event_types'),
    ]

    operations = [
    ]
