# Generated by Django 6.0.6 on 2026-06-23 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_auditlog_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RBACRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('capabilities', models.JSONField(default=list)),
                ('is_system', models.BooleanField(default=False)),
                ('is_immutable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'RBAC Role',
                'verbose_name_plural': 'RBAC Roles',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='netpulseuser',
            name='rbac_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.rbacrole'),
        ),
    ]
