# Generated by Django 6.0.6 on 2026-06-24 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_resync_rbac_roles_phase_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_role_changed', 'User Role Changed'), ('device_created', 'Device Created'), ('device_updated', 'Device Updated'), ('device_deleted', 'Device Deleted'), ('device_approved', 'Device Approved'), ('device_rejected', 'Device Rejected'), ('topology_link_created', 'Manual Topology Link Created'), ('topology_link_updated', 'Manual Topology Link Updated'), ('topology_link_deleted', 'Manual Topology Link Deleted'), ('config_pushed', 'Config Pushed to Device'), ('config_backup', 'Config Backup Taken'), ('config_restored', 'Config Restored'), ('compliance_run', 'Compliance Check Run'), ('credential_created', 'Credential Created'), ('credential_updated', 'Credential Updated'), ('credential_deleted', 'Credential Deleted'), ('credential_accessed', 'Credential Accessed'), ('discovery_started', 'Discovery Started'), ('discovery_completed', 'Discovery Completed'), ('netbox_import', 'NetBox Import'), ('unifi_sync', 'UniFi Sync'), ('mist_sync', 'Mist Sync'), ('settings_changed', 'Settings Changed'), ('api_key_created', 'API Key Created'), ('api_key_deleted', 'API Key Deleted'), ('sso_config_changed', 'SSO Config Changed'), ('alert_acknowledged', 'Alert Acknowledged'), ('alert_resolved', 'Alert Resolved'), ('alert_rule_created', 'Alert Rule Created'), ('alert_rule_updated', 'Alert Rule Updated'), ('alert_rule_deleted', 'Alert Rule Deleted'), ('site_created', 'Site Created'), ('site_updated', 'Site Updated'), ('site_deleted', 'Site Deleted'), ('agent_enrolled', 'Agent Enrolled'), ('agent_revoked', 'Agent Revoked'), ('chatops_query', 'ChatOps Query'), ('chatops_denied', 'ChatOps Query Denied'), ('mfa_enabled', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('mfa_failed', 'MFA Verification Failed'), ('mfa_reset_by_admin', 'MFA Reset by Admin'), ('mfa_enrollment_forced', 'MFA Enrollment Forced'), ('mfa_enrollment_completed', 'MFA Enrollment Completed')], db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='MFADevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('secret_encrypted', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_step', models.BigIntegerField(blank=True, null=True)),
                ('recovery_codes', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
