# Generated by Django 6.0.5 on 2026-05-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='netboximport',
            name='devices_updated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
