# Generated by Django 6.0.6 on 2026-06-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_netboximport_devices_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('custom', 'Custom SMTP'), ('gmail', 'Gmail'), ('m365', 'Microsoft 365'), ('sendgrid', 'SendGrid'), ('mailgun', 'Mailgun')], default='custom', max_length=20)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.IntegerField(default=587)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('from_email', models.CharField(blank=True, max_length=255)),
                ('from_name', models.CharField(default='NetPulse', max_length=128)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
    ]
