# Generated by Django 6.0.6 on 2026-06-07 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0023_alter_device_platform'),
        ('integrations', '0003_emailsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('host', models.CharField(help_text='Controller hostname or IP', max_length=255)),
                ('port', models.IntegerField(default=8443)),
                ('username', models.CharField(max_length=128)),
                ('verify_ssl', models.BooleanField(default=False)),
                ('unifi_site_id', models.CharField(default='default', help_text='UniFi site ID (default=default)', max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=512)),
                ('device_count', models.IntegerField(default=0)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unifi_controllers', to='devices.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
