# Generated by Django 6.0.6 on 2026-06-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_unificontroller'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiCloudAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='UniFi Cloud Account', max_length=128)),
                ('enabled', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=512)),
                ('host_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'UniFi Cloud Account',
                'verbose_name_plural': 'UniFi Cloud Account',
            },
        ),
        migrations.AddField(
            model_name='unificontroller',
            name='cloud_host_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
