# Generated by Django 6.0.6 on 2026-06-09 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0024_lldpneighbor'),
        ('integrations', '0006_unificontroller_model_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiApStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(default=0, help_text='UniFi state: 1=connected, 0=disconnected')),
                ('satisfaction', models.IntegerField(blank=True, help_text='UniFi health score 0-100', null=True)),
                ('client_count', models.IntegerField(default=0)),
                ('cpu_pct', models.FloatField(blank=True, null=True)),
                ('memory_pct', models.FloatField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('uptime_seconds', models.BigIntegerField(blank=True, null=True)),
                ('uplink_speed_mbps', models.IntegerField(blank=True, null=True)),
                ('uplink_type', models.CharField(blank=True, max_length=16)),
                ('radios', models.JSONField(default=list)),
                ('last_collected', models.DateTimeField(blank=True, null=True)),
                ('controller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_statuses', to='integrations.unificontroller')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unifi_ap_status', to='devices.device')),
            ],
            options={
                'verbose_name': 'UniFi AP Status',
                'verbose_name_plural': 'UniFi AP Statuses',
            },
        ),
    ]
