# Generated by Django 6.0.6 on 2026-06-09 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0025_alter_device_platform'),
        ('integrations', '0007_unifiapstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiConsoleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(default=0, help_text='UniFi state: 1=connected, 0=disconnected')),
                ('satisfaction', models.IntegerField(blank=True, help_text='UniFi health score 0-100', null=True)),
                ('cpu_pct', models.FloatField(blank=True, null=True)),
                ('memory_pct', models.FloatField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('uptime_seconds', models.BigIntegerField(blank=True, null=True)),
                ('loadavg_1', models.FloatField(blank=True, null=True)),
                ('loadavg_5', models.FloatField(blank=True, null=True)),
                ('loadavg_15', models.FloatField(blank=True, null=True)),
                ('num_adopted', models.IntegerField(default=0)),
                ('num_disconnected', models.IntegerField(default=0)),
                ('num_pending', models.IntegerField(default=0)),
                ('wans', models.JSONField(default=list)),
                ('last_collected', models.DateTimeField(blank=True, null=True)),
                ('controller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='console_statuses', to='integrations.unificontroller')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unifi_console_status', to='devices.device')),
            ],
            options={
                'verbose_name': 'UniFi Console Status',
                'verbose_name_plural': 'UniFi Console Statuses',
            },
        ),
    ]
