# Generated by Django 6.0.6 on 2026-06-09 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_sitecredential'),
        ('integrations', '0008_unificonsolestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='unificontroller',
            name='credential_profile',
            field=models.ForeignKey(blank=True, help_text='Credential profile for local controller API access (HTTPS credentials recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unifi_controllers', to='credentials.credentialprofile'),
        ),
        migrations.AlterField(
            model_name='unificontroller',
            name='username',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
