# Generated by Django 6.0.6 on 2026-06-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_netboximport_verify_ssl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='from_name',
            field=models.CharField(default='spane', max_length=128),
        ),
    ]
