# Generated by Django 6.0.6 on 2026-06-13 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0028_alter_device_platform'),
        ('integrations', '0012_alter_emailsettings_from_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MistIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Mist', max_length=128)),
                ('org_id', models.CharField(blank=True, help_text='Auto-populated from the API', max_length=64)),
                ('org_name', models.CharField(blank=True, max_length=128)),
                ('enabled', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=512)),
                ('site_count', models.IntegerField(default=0)),
                ('device_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mist Integration',
                'verbose_name_plural': 'Mist Integration',
            },
        ),
        migrations.CreateModel(
            name='MistSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mist_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=4)),
                ('device_count', models.IntegerField(default=0)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mist_sites', to='devices.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
