# Generated by Django 6.0.6 on 2026-06-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_mistintegration_mistsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistintegration',
            name='api_host',
            field=models.CharField(default='api.mist.com', help_text='API endpoint for your region. Find it from your portal URL: manage.XX.mist.com → api.XX.mist.com', max_length=128),
        ),
    ]
