# Generated by Django 6.0.5 on 2026-05-31 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0009_device_unreachable_since'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('check_type', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP (ping)'), ('dns', 'DNS'), ('tls', 'TLS certificate'), ('smtp', 'SMTP'), ('ftp', 'FTP'), ('ssh', 'SSH'), ('ldap', 'LDAP'), ('custom', 'Custom')], db_index=True, max_length=10)),
                ('host', models.CharField(help_text='IP or hostname to probe.', max_length=255)),
                ('port', models.IntegerField(blank=True, help_text='Defaults from check_type when unset.', null=True)),
                ('interval_seconds', models.IntegerField(default=60)),
                ('timeout_seconds', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Pause scheduling without deleting.')),
                ('current_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('degraded', 'Degraded'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=10)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_status_change', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('failures_before_alert', models.IntegerField(default=2)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('response_time_warning_ms', models.IntegerField(blank=True, null=True)),
                ('response_time_critical_ms', models.IntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('device', models.ForeignKey(blank=True, help_text='Network device/server this check is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_checks', to='devices.device')),
                ('site', models.ForeignKey(blank=True, help_text='Site this check belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_checks', to='devices.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('degraded', 'Degraded'), ('unknown', 'Unknown')], max_length=10)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(db_index=True)),
                ('error', models.CharField(blank=True, max_length=512)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('service_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='checks.servicecheck')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='servicecheck',
            index=models.Index(fields=['check_type', 'current_status'], name='checks_serv_check_t_c3c227_idx'),
        ),
        migrations.AddIndex(
            model_name='checkresult',
            index=models.Index(fields=['service_check', '-checked_at'], name='checks_chec_service_605750_idx'),
        ),
    ]
