# Generated by Django 6.0.5 on 2026-05-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecheck',
            name='check_type',
            field=models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP (ping)'), ('dns', 'DNS'), ('tls', 'TLS certificate'), ('smtp', 'SMTP'), ('ftp', 'FTP'), ('ssh', 'SSH'), ('ssh_banner', 'SSH banner'), ('ldap', 'LDAP'), ('custom', 'Custom')], db_index=True, max_length=10),
        ),
    ]
