# Generated by Django 6.0.5 on 2026-05-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_alter_servicecheck_check_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecheck',
            name='alert_on_degraded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecheck',
            name='alert_on_down',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicecheck',
            name='alert_on_recovery',
            field=models.BooleanField(default=True),
        ),
    ]
