# Generated by Django 6.0.6 on 2026-06-08 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0004_servicecheck_radius_tacacs'),
        ('collectors', '0003_collector_type_capabilities_hostname_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkresult',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_results', to='collectors.collector'),
        ),
        migrations.AddField(
            model_name='servicecheck',
            name='collector_mode',
            field=models.CharField(choices=[('all', 'All Collectors'), ('any', 'Any One Collector'), ('selected', 'Selected Collectors'), ('site', 'Same Site as Device')], default='site', help_text="all=pass from every collector · any=pass if one passes · selected=specific collectors · site=collectors at device's site", max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceCheckCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_result', models.CharField(choices=[('passing', 'Passing'), ('failing', 'Failing'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_latency_ms', models.FloatField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=512)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_assignments', to='collectors.collector')),
                ('service_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector_assignments', to='checks.servicecheck')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='servicecheck',
            name='collectors',
            field=models.ManyToManyField(blank=True, help_text="Collectors that run this check (used by the 'selected' mode).", related_name='service_checks', through='checks.ServiceCheckCollector', to='collectors.collector'),
        ),
        migrations.AddIndex(
            model_name='servicecheckcollector',
            index=models.Index(fields=['service_check', 'collector'], name='checks_serv_service_468339_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicecheckcollector',
            unique_together={('service_check', 'collector')},
        ),
    ]
