# Generated by Django 6.0.5 on 2026-05-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('api_key_hash', models.CharField(max_length=128, unique=True)),
                ('cert_serial', models.CharField(blank=True, max_length=128)),
                ('cert_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Registration'), ('active', 'Active'), ('offline', 'Offline'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=10)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
