# Generated by Django 6.0.5 on 2026-05-30 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0001_initial'),
        ('devices', '0006_topologylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='collector_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collector',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectors', to='devices.site'),
        ),
    ]
