# Generated by Django 6.0.6 on 2026-06-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0003_collector_type_capabilities_hostname_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='api_key_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='cert_fingerprint_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=95),
        ),
        migrations.AddField(
            model_name='collector',
            name='enrolled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='enrollment_token_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='collector',
            name='nats_account',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
