server_name: internal
listen: 0.0.0.0:4222
http:   0.0.0.0:8222
authorization { user: npuser, password: nppass }
leafnodes { remotes: [ { url: "nats://interproxy:7422", credentials: "/creds/AGG.creds" } ] }
