# Generated by Django 6.0.5 on 2026-05-29 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('credential_type', models.CharField(choices=[('snmpv1', 'SNMP v1'), ('snmpv2c', 'SNMP v2c'), ('snmpv3', 'SNMP v3'), ('ssh_password', 'SSH (password)'), ('ssh_key', 'SSH (key)'), ('http_basic', 'HTTP Basic Auth'), ('http_token', 'HTTP Bearer Token'), ('http_apikey', 'HTTP API Key'), ('gnmi', 'gNMI'), ('netconf', 'NETCONF')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('vault_path', models.CharField(blank=True, max_length=512)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('auth_method', models.CharField(blank=True, choices=[('password', 'Password'), ('key', 'SSH Key'), ('token', 'Token'), ('apikey', 'API Key'), ('community', 'Community String')], max_length=20)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('tls_enabled', models.BooleanField(default=False)),
                ('snmp_version', models.CharField(blank=True, choices=[('1', 'v1'), ('2c', 'v2c'), ('3', 'v3')], max_length=4)),
                ('snmp_security_level', models.CharField(blank=True, choices=[('noAuthNoPriv', 'noAuthNoPriv'), ('authNoPriv', 'authNoPriv'), ('authPriv', 'authPriv')], max_length=16)),
                ('auth_protocol', models.CharField(blank=True, max_length=16)),
                ('priv_protocol', models.CharField(blank=True, max_length=16)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('last_test_result', models.CharField(choices=[('untested', 'Untested'), ('success', 'Success'), ('failure', 'Failure')], default='untested', max_length=10)),
                ('last_test_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('snmp_polling', 'SNMP Polling'), ('ssh_config', 'SSH (config push)'), ('ssh_backup', 'SSH (config backup)'), ('netconf', 'NETCONF'), ('gnmi', 'gNMI'), ('http_api', 'HTTP API')], db_index=True, max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_links', to='credentials.credentialprofile')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_links', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='credentialprofile',
            index=models.Index(fields=['credential_type', 'name'], name='credentials_credent_34242a_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecredential',
            index=models.Index(fields=['device', 'purpose'], name='credentials_device__518c82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicecredential',
            unique_together={('device', 'purpose')},
        ),
    ]
