# Generated by Django 6.0.5 on 2026-05-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devicecredential',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='devicecredential',
            name='credentials_device__518c82_idx',
        ),
        migrations.RemoveIndex(
            model_name='credentialprofile',
            name='credentials_credent_34242a_idx',
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='gnmi_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='gnmi_port',
            field=models.PositiveIntegerField(default=57400),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='gnmi_tls_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='gnmi_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='https_auth_type',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('token', 'Bearer Token'), ('apikey', 'API Key')], max_length=10),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='https_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='https_port',
            field=models.PositiveIntegerField(default=443),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='https_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='https_verify_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='netconf_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='netconf_port',
            field=models.PositiveIntegerField(default=830),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='netconf_use_ssh_creds',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='netconf_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='snmpv2c_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='snmpv2c_port',
            field=models.PositiveIntegerField(default=161),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='snmpv3_auth_protocol',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='snmpv3_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='snmpv3_port',
            field=models.PositiveIntegerField(default=161),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='snmpv3_priv_protocol',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='snmpv3_security_level',
            field=models.CharField(blank=True, choices=[('noAuthNoPriv', 'noAuthNoPriv'), ('authNoPriv', 'authNoPriv'), ('authPriv', 'authPriv')], max_length=16),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='snmpv3_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='ssh_auth_method',
            field=models.CharField(blank=True, choices=[('password', 'Password'), ('key', 'SSH Key')], max_length=10),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='ssh_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='ssh_port',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='ssh_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='credentialprofile',
            name='last_test_result',
            field=models.CharField(choices=[('untested', 'Untested'), ('success', 'Success'), ('partial', 'Partial'), ('failure', 'Failure')], default='untested', max_length=10),
        ),
        migrations.RemoveField(
            model_name='devicecredential',
            name='credential',
        ),
        migrations.RemoveField(
            model_name='devicecredential',
            name='device',
        ),
        migrations.RemoveField(
            model_name='credentialprofile',
            name='auth_method',
        ),
        migrations.RemoveField(
            model_name='credentialprofile',
            name='auth_protocol',
        ),
        migrations.RemoveField(
            model_name='credentialprofile',
            name='credential_type',
        ),
        migrations.RemoveField(
            model_name='credentialprofile',
            name='port',
        ),
        migrations.RemoveField(
            model_name='credentialprofile',
            name='priv_protocol',
        ),
        migrations.RemoveField(
            model_name='credentialprofile',
            name='snmp_security_level',
        ),
        migrations.RemoveField(
            model_name='credentialprofile',
            name='snmp_version',
        ),
        migrations.RemoveField(
            model_name='credentialprofile',
            name='tls_enabled',
        ),
        migrations.RemoveField(
            model_name='credentialprofile',
            name='username',
        ),
    ]
