# Generated by Django 6.0.5 on 2026-05-29 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_alter_devicecredential_unique_together_and_more'),
        ('devices', '0003_remove_device_credentials_device_credential_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceCredential',
        ),
    ]
