# Generated by Django 6.0.6 on 2026-06-07 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_delete_devicecredential'),
        ('devices', '0023_alter_device_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=100, help_text='Lower = higher priority. More specific rules win.')),
                ('credential_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_credentials', to='credentials.credentialprofile')),
                ('role', models.ForeignKey(blank=True, help_text='Leave blank to apply to all roles at this site', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_credentials', to='devices.devicerole')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_credentials', to='devices.site')),
            ],
            options={
                'ordering': ['priority'],
                'unique_together': {('site', 'role', 'credential_profile')},
            },
        ),
    ]
