# Generated by Django 6.0.6 on 2026-06-14 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('compliance_summary', 'Compliance Summary'), ('daily_ops', 'Daily Operations')], max_length=32)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=16)),
                ('hour', models.PositiveSmallIntegerField(default=8, help_text='Hour of day (UTC), 0-23')),
                ('day_of_week', models.PositiveSmallIntegerField(default=0, help_text='0=Mon … 6=Sun (weekly only)')),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, help_text='1-28 (monthly only)')),
                ('fmt', models.CharField(default='pdf', max_length=10)),
                ('recipients', models.JSONField(default=list, help_text='Email addresses')),
                ('parameters', models.JSONField(default=dict, help_text='Report build params (site_ids, group_by, …)')),
                ('enabled', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['report_type', 'frequency'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('compliance_summary', 'Compliance Summary'), ('daily_ops', 'Daily Operations')], db_index=True, max_length=32)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(default='on-demand', max_length=32)),
                ('parameters', models.JSONField(default=dict)),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('format', models.CharField(default='pdf', max_length=10)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type', '-generated_at'], name='reports_gen_report__d504b6_idx')],
            },
        ),
    ]
