# Generated by Django 6.0.5 on 2026-05-30 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0005_device_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_method', models.CharField(choices=[('snmp', 'SNMP'), ('gnmi', 'gNMI'), ('both', 'Both')], default='snmp', max_length=8)),
                ('snmp_interval', models.IntegerField(default=300)),
                ('gnmi_interval', models.IntegerField(default=30)),
                ('collect_cpu', models.BooleanField(default=True)),
                ('collect_memory', models.BooleanField(default=True)),
                ('collect_temperature', models.BooleanField(default=True)),
                ('collect_power', models.BooleanField(default=True)),
                ('collect_fans', models.BooleanField(default=True)),
                ('collect_bgp', models.BooleanField(default=True)),
                ('collect_inventory', models.BooleanField(default=True)),
                ('collect_lldp', models.BooleanField(default=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_config', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonitoredInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('if_index', models.IntegerField(blank=True, null=True)),
                ('if_name', models.CharField(max_length=255)),
                ('if_description', models.CharField(blank=True, max_length=255)),
                ('if_speed_mbps', models.IntegerField(blank=True, null=True)),
                ('if_type', models.CharField(blank=True, max_length=64)),
                ('lldp_neighbor_hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('lldp_neighbor_port', models.CharField(blank=True, max_length=255, null=True)),
                ('lldp_neighbor_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('poll_traffic', models.BooleanField(default=True)),
                ('poll_errors', models.BooleanField(default=True)),
                ('poll_status', models.BooleanField(default=True)),
                ('collection_method', models.CharField(choices=[('auto', 'Auto'), ('snmp', 'SNMP'), ('gnmi', 'gNMI')], default='auto', max_length=8)),
                ('last_discovered', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(default='unknown', max_length=16)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_interfaces', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['device', 'if_name'], name='telemetry_m_device__952c86_idx')],
                'unique_together': {('device', 'if_name')},
            },
        ),
    ]
