# Generated by Django 6.0.5 on 2026-05-30 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_last_seen'),
        ('telemetry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sections', models.JSONField(default=list)),
                ('success', models.BooleanField(default=False)),
                ('output', models.TextField(blank=True)),
                ('errors', models.JSONField(default=list)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_pushes', to='devices.device')),
                ('pushed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_pushes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['device', '-created_at'], name='telemetry_c_device__a8ceda_idx')],
            },
        ),
    ]
