# Generated by Django 6.0.5 on 2026-05-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_configpush'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNMPGlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_metrics_interval', models.IntegerField(default=300)),
                ('interface_traffic_interval', models.IntegerField(default=300)),
                ('interface_status_interval', models.IntegerField(default=60)),
                ('bgp_interval', models.IntegerField(default=60)),
                ('inventory_interval', models.IntegerField(default=3600)),
                ('lldp_interval', models.IntegerField(default=3600)),
                ('max_concurrent_sessions', models.IntegerField(default=10)),
                ('snmp_timeout', models.IntegerField(default=5)),
                ('snmp_retries', models.IntegerField(default=3)),
                ('bulk_get_enabled', models.BooleanField(default=True)),
                ('bulk_get_max_repetitions', models.IntegerField(default=25)),
            ],
            options={
                'verbose_name': 'SNMP global settings',
                'verbose_name_plural': 'SNMP global settings',
            },
        ),
        migrations.AddField(
            model_name='telemetryconfig',
            name='bgp_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryconfig',
            name='device_metrics_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryconfig',
            name='interface_status_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryconfig',
            name='interface_traffic_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryconfig',
            name='override_intervals',
            field=models.BooleanField(default=False),
        ),
    ]
