# Generated by Django 6.0.5 on 2026-05-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_snmpglobalsettings_telemetryconfig_bgp_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredinterface',
            name='alert_on_down',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monitoredinterface',
            name='alert_on_up',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monitoredinterface',
            name='alert_severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', max_length=10),
        ),
        migrations.AddField(
            model_name='monitoredinterface',
            name='consecutive_polls_before_alert',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='monitoredinterface',
            name='last_status_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
