# Generated by Django 6.0.5 on 2026-05-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevent',
            name='resolution_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='resolved_by',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
