# Generated by Django 6.0.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alertevent_resolution_note_alertevent_resolved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
