# Generated by Django 6.0.6 on 2026-07-01 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_alertrule_kind'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='alerts_noti_channel_05c10b_idx',
            old_name='alerts_noti_channel_4d8f9e_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='alerts_noti_status_0d187b_idx',
            old_name='alerts_noti_status_7c1a2b_idx',
        ),
    ]
