# Generated by Django 6.0.5 on 2026-05-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('common_name', models.CharField(blank=True, max_length=255)),
                ('sans', models.JSONField(blank=True, default=list)),
                ('issuer', models.CharField(blank=True, max_length=512)),
                ('serial', models.CharField(blank=True, max_length=128)),
                ('fingerprint_sha256', models.CharField(blank=True, max_length=128)),
                ('not_before', models.DateTimeField(blank=True, null=True)),
                ('not_after', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, choices=[('self_signed', 'Self-signed'), ('csr', 'CA-signed (CSR)'), ('uploaded', 'Uploaded')], max_length=20)),
                ('installed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'server certificate',
                'verbose_name_plural': 'server certificate',
            },
        ),
    ]
