# Generated by Django 6.0.5 on 2026-05-30 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CACertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Admin-friendly label', max_length=255)),
                ('subject', models.CharField(blank=True, max_length=512)),
                ('issuer', models.CharField(blank=True, max_length=512)),
                ('fingerprint_sha256', models.CharField(max_length=128, unique=True)),
                ('not_before', models.DateTimeField(blank=True, null=True)),
                ('not_after', models.DateTimeField(blank=True, null=True)),
                ('cert_pem', models.TextField()),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('is_root', models.BooleanField(default=False)),
                ('is_intermediate', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ca_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CA certificate',
                'verbose_name_plural': 'CA certificates',
                'ordering': ['subject'],
            },
        ),
    ]
