# Generated by Django 6.0.6 on 2026-06-22 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPushTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "AOS-CX SNMP v3"', max_length=128)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('snmp', 'SNMP'), ('syslog', 'Syslog'), ('ntp', 'NTP'), ('dns', 'DNS'), ('aaa', 'AAA/RADIUS'), ('banner', 'Banner/MOTD'), ('logging', 'Logging'), ('other', 'Other')], default='other', max_length=32)),
                ('platform', models.CharField(blank=True, help_text='e.g. aos_cx, ios; leave blank to allow all platforms', max_length=64)),
                ('template_content', models.TextField(help_text='Jinja2 template. Available variables: {{ device }}, {{ site }}, {{ settings }} plus any you define.')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Default variable values for this template')),
                ('enabled', models.BooleanField(default=True)),
                ('builtin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_push_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
