# Generated by Django 6.0.5 on 2026-05-29 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(db_index=True, decimal_places=2, max_digits=5)),
                ('cve_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('compliance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('lifecycle_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('anomaly_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_score', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
