# Generated by Django 6.0.5 on 2026-05-31 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerting', '0001_initial'),
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slack_webhook_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='OnCallSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Primary On-Call', max_length=255)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='alerting.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OnCallShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('recurrence', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='none', max_length=8)),
                ('recurrence_days', models.JSONField(blank=True, default=list)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='alerting.oncallschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oncall_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_datetime'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlertAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ack_alerts', to=settings.AUTH_USER_MODEL)),
                ('alert_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='alerts.alertevent')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['alert_event', '-acknowledged_at'], name='alerting_al_alert_e_e58924_idx')],
            },
        ),
    ]
