# Generated by Django 6.0.5 on 2026-05-31 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerting', '0002_team_slack_webhook_url_oncallschedule_oncallshift_and_more'),
        ('devices', '0011_alter_topologylink_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('recurrence', models.CharField(choices=[('none', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=8)),
                ('recurrence_end', models.DateTimeField(blank=True, null=True)),
                ('recurrence_days', models.JSONField(blank=True, default=list)),
                ('check_types', models.JSONField(blank=True, default=list)),
                ('severity_filter', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_windows', to=settings.AUTH_USER_MODEL)),
                ('devices', models.ManyToManyField(blank=True, related_name='maintenance_windows', to='devices.device')),
                ('sites', models.ManyToManyField(blank=True, related_name='maintenance_windows', to='devices.site')),
            ],
            options={
                'ordering': ['start_time'],
                'abstract': False,
            },
        ),
    ]
