# Generated by Django 6.0.5 on 2026-05-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerting', '0003_maintenancewindow'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='discord_webhook_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
