# Generated by Django 6.0.5 on 2026-06-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerting', '0004_team_discord_webhook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='notify_discord',
            field=models.BooleanField(default=False),
        ),
    ]
