# Generated by Django 6.0.5 on 2026-05-29 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0004_site_address_site_city_site_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_enabled', models.BooleanField(default=True)),
                ('local_path', models.CharField(default='/opt/netpulse/configs', max_length=512)),
                ('local_retention_days', models.PositiveIntegerField(default=90)),
                ('git_enabled', models.BooleanField(default=False)),
                ('git_provider', models.CharField(blank=True, choices=[('github', 'GitHub'), ('gitlab_cloud', 'GitLab (cloud)'), ('gitlab_self', 'GitLab (self-hosted)'), ('gitea', 'Gitea'), ('bitbucket', 'Bitbucket'), ('generic_https', 'Generic HTTPS'), ('generic_ssh', 'Generic SSH')], max_length=20)),
                ('git_repo_url', models.CharField(blank=True, max_length=512)),
                ('git_branch', models.CharField(default='main', max_length=255)),
                ('git_auth_method', models.CharField(blank=True, choices=[('token', 'Personal Access Token'), ('ssh_key', 'SSH Key'), ('deploy_key', 'Deploy Key')], max_length=20)),
                ('git_vault_path', models.CharField(blank=True, max_length=512)),
                ('git_commit_author', models.CharField(default='NetPulse Config Manager', max_length=255)),
                ('git_commit_email', models.EmailField(blank=True, max_length=254)),
                ('git_sync_frequency', models.CharField(choices=[('on_backup', 'On every backup'), ('hourly', 'Hourly'), ('daily', 'Daily')], default='on_backup', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_success', models.BooleanField(null=True)),
                ('last_commit_sha', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Configuration backup settings',
                'verbose_name_plural': 'Configuration backup settings',
            },
        ),
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config_type', models.CharField(choices=[('running', 'Running'), ('startup', 'Startup'), ('candidate', 'Candidate')], db_index=True, default='running', max_length=10)),
                ('collected_at', models.DateTimeField(db_index=True)),
                ('collected_by', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('drift_detected', 'Drift detected')], default='scheduled', max_length=16)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('changed_from_previous', models.BooleanField(default=False)),
                ('diff_summary', models.TextField(blank=True, null=True)),
                ('git_commit_sha', models.CharField(blank=True, max_length=64)),
                ('local_path', models.CharField(blank=True, max_length=512)),
                ('compliance_status', models.CharField(blank=True, max_length=32)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['device', 'config_type', '-collected_at'], name='configbacku_device__1c4943_idx')],
            },
        ),
    ]
