# Generated by Django 6.0.6 on 2026-06-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configbackup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configbackupsettings',
            name='git_commit_author',
            field=models.CharField(default='spane Config Manager', max_length=255),
        ),
    ]
