# Generated by Django 6.0.6 on 2026-06-14 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configbackup', '0002_alter_configbackupsettings_git_commit_author'),
        ('devices', '0029_normalize_lldp_capabilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigCollectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('unchanged', 'Unchanged'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('auth_failed', 'Auth Failed'), ('empty', 'Empty Response')], max_length=20)),
                ('collected_by', models.CharField(default='scheduled', help_text='scheduled, manual, api, enrichment', max_length=64)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Collection duration in milliseconds', null=True)),
                ('error_message', models.CharField(blank=True, max_length=512)),
                ('config_changed', models.BooleanField(help_text='None if not reached; True/False when reached', null=True)),
                ('bytes_collected', models.IntegerField(blank=True, null=True)),
                ('method', models.CharField(blank=True, help_text='rest, ssh, netconf, netmiko', max_length=32)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_logs', to='devices.device')),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['device', '-collected_at'], name='configbacku_device__05f9ec_idx'), models.Index(fields=['-collected_at'], name='configbacku_collect_db8208_idx'), models.Index(fields=['status'], name='configbacku_status_99d5f1_idx')],
            },
        ),
    ]
