# Generated by Django 6.0.6 on 2026-06-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configbackup', '0003_configcollectionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfig',
            name='startup_checked_at',
            field=models.DateTimeField(blank=True, help_text='When the startup match was last checked.', null=True),
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='startup_diff',
            field=models.TextField(blank=True, help_text='Diff between running and startup configs if they differ.'),
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='startup_match',
            field=models.BooleanField(help_text='True if running config matches startup config; None if not checked.', null=True),
        ),
    ]
