# Generated by Django 6.0.6 on 2026-06-14 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('sox', 'SOX (ITGC)'), ('iso27001', 'ISO/IEC 27001'), ('nist_csf', 'NIST CSF'), ('pci_dss', 'PCI-DSS'), ('hipaa', 'HIPAA Security Rule'), ('cis', 'CIS Controls v8')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=32)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FrameworkControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control_id', models.CharField(help_text="e.g. 'PCI-DSS 2.2' or 'CIS 4.1'", max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('mapping_key', models.CharField(max_length=64)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='frameworks.regulatoryframework')),
            ],
            options={
                'ordering': ['framework', 'control_id'],
                'constraints': [models.UniqueConstraint(fields=('framework', 'control_id'), name='uniq_framework_control')],
            },
        ),
    ]
