# Generated by Django 6.0.5 on 2026-05-29 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone_type', models.CharField(choices=[('eos', 'End of Sale'), ('eosm', 'End of Software Maintenance'), ('eoss', 'End of Security Support'), ('eol', 'End of Life')], db_index=True, max_length=10)),
                ('milestone_date', models.DateField(db_index=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_milestones', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('device', 'milestone_type')},
            },
        ),
    ]
