# Generated by Django 6.0.5 on 2026-05-29 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostname', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('platform', models.CharField(choices=[('ios', 'Cisco IOS'), ('ios_xe', 'Cisco IOS-XE'), ('ios_xr', 'Cisco IOS-XR'), ('nxos', 'Cisco NX-OS'), ('eos', 'Arista EOS'), ('junos', 'Juniper JunOS'), ('sonic', 'SONiC'), ('other', 'Other')], default='other', max_length=20)),
                ('os_version', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('decommissioned', 'Decommissioned')], db_index=True, default='active', max_length=20)),
                ('credential_path', models.CharField(blank=True, max_length=512)),
                ('notes', models.TextField(blank=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='devices', to='devices.devicegroup')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscoveryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('passive', 'Passive (ingest source IPs)'), ('topology', 'Topology Walk (CDP/LLDP/route table)'), ('scan', 'Active Scan (SNMP/SSH probe)'), ('import', 'Import (NetBox/CSV)')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('subnets', models.JSONField(default=list)),
                ('allowed_subnets', models.JSONField(default=list)),
                ('excluded_subnets', models.JSONField(default=list)),
                ('max_depth', models.PositiveIntegerField(default=10)),
                ('max_devices', models.PositiveIntegerField(default=1000)),
                ('rate_limit_pps', models.PositiveIntegerField(default=10)),
                ('devices_found', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_jobs', to=settings.AUTH_USER_MODEL)),
                ('seed_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seeded_discovery_jobs', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscoveredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_ip', models.GenericIPAddressField(db_index=True)),
                ('detection_methods', models.JSONField(default=list)),
                ('responds_to', models.JSONField(default=dict)),
                ('confidence_score', models.PositiveSmallIntegerField(default=0)),
                ('discovered_hostname', models.CharField(blank=True, max_length=255)),
                ('discovered_vendor', models.CharField(blank=True, max_length=100)),
                ('discovered_platform', models.CharField(blank=True, max_length=100)),
                ('discovered_model', models.CharField(blank=True, max_length=100)),
                ('discovered_os', models.CharField(blank=True, max_length=100)),
                ('raw_fingerprint', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_discoveries', to=settings.AUTH_USER_MODEL)),
                ('approved_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_sources', to='devices.device')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_devices', to='devices.discoveryjob')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='discoveryjob',
            index=models.Index(fields=['status', '-created_at'], name='devices_dis_status_334ffc_idx'),
        ),
        migrations.AddIndex(
            model_name='discovereddevice',
            index=models.Index(fields=['status', '-confidence_score'], name='devices_dis_status_a9c352_idx'),
        ),
        migrations.AddIndex(
            model_name='discovereddevice',
            index=models.Index(fields=['source_ip'], name='devices_dis_source__768aa0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='discovereddevice',
            unique_together={('job', 'source_ip')},
        ),
    ]
