# Generated by Django 6.0.5 on 2026-05-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='credential_path',
        ),
        migrations.AddField(
            model_name='device',
            name='credentials',
            field=models.ManyToManyField(blank=True, related_name='devices', through='credentials.DeviceCredential', to='credentials.credentialprofile'),
        ),
    ]
