# Generated by Django 6.0.5 on 2026-05-29 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_alter_devicecredential_unique_together_and_more'),
        ('devices', '0002_remove_device_credential_path_device_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='credentials',
        ),
        migrations.AddField(
            model_name='device',
            name='credential_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='credentials.credentialprofile'),
        ),
    ]
