# Generated by Django 6.0.5 on 2026-05-30 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopologyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('port_a', models.CharField(max_length=255)),
                ('port_b', models.CharField(blank=True, max_length=255)),
                ('discovered_via', models.CharField(default='lldp', max_length=20)),
                ('link_speed_mbps', models.IntegerField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('device_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_a', to='devices.device')),
                ('device_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_b', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['device_a'], name='devices_top_device__1b4158_idx'), models.Index(fields=['device_b'], name='devices_top_device__9f2849_idx')],
                'unique_together': {('device_a', 'port_a')},
            },
        ),
    ]
