# Generated by Django 6.0.5 on 2026-05-30 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0002_collector_collector_ip_collector_is_default_and_more'),
        ('devices', '0006_topologylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='collectors.collector'),
        ),
        migrations.AddField(
            model_name='site',
            name='default_collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_sites', to='collectors.collector'),
        ),
    ]
