# Generated by Django 6.0.5 on 2026-05-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_device_collector_site_default_collector'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='consecutive_failures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='is_reachable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_reachability_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='reachability_method',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('unreachable', 'Unreachable'), ('maintenance', 'Maintenance'), ('decommissioned', 'Decommissioned')], db_index=True, default='active', max_length=20),
        ),
    ]
