# Generated by Django 6.0.5 on 2026-05-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_device_consecutive_failures_device_is_reachable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='unreachable_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
