# Generated by Django 6.0.5 on 2026-05-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_device_unreachable_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='platform',
            field=models.CharField(choices=[('ios', 'Cisco IOS'), ('ios_xe', 'Cisco IOS-XE'), ('ios_xr', 'Cisco IOS-XR'), ('nxos', 'Cisco NX-OS'), ('eos', 'Arista EOS'), ('junos', 'Juniper JunOS'), ('fortios', 'Fortinet FortiOS'), ('panos', 'Palo Alto PAN-OS'), ('sonic', 'SONiC'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
