# Generated by Django 6.0.5 on 2026-05-31 18:13

from django.db import migrations, models


def dedup_topology_links(apps, schema_editor):
    """
    Collapse existing rows to their canonical (lower device id = device_a) tuple,
    deleting duplicates, so the new UniqueConstraint can be added cleanly.
    """
    TopologyLink = apps.get_model("devices", "TopologyLink")
    seen = {}
    for link in TopologyLink.objects.order_by("id"):
        if link.device_a_id and link.device_b_id and link.device_a_id > link.device_b_id:
            key = (link.device_b_id, link.port_b, link.device_a_id, link.port_a)
        else:
            key = (link.device_a_id, link.port_a, link.device_b_id, link.port_b)
        if key in seen:
            link.delete()
        else:
            seen[key] = link.id


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_alter_device_platform'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topologylink',
            unique_together=set(),
        ),
        # Dedup BEFORE adding the constraint, or AddConstraint fails on dupes.
        migrations.RunPython(dedup_topology_links, noop),
        migrations.AddConstraint(
            model_name='topologylink',
            constraint=models.UniqueConstraint(fields=('device_a', 'port_a', 'device_b', 'port_b'), name='unique_topology_link'),
        ),
    ]
