# Generated by Django 6.0.5 on 2026-06-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_canonicalize_topology_ports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='platform',
            field=models.CharField(choices=[('ios', 'Cisco IOS'), ('ios_xe', 'Cisco IOS-XE'), ('ios_xr', 'Cisco IOS-XR'), ('nxos', 'Cisco NX-OS'), ('eos', 'Arista EOS'), ('junos', 'Juniper JunOS'), ('fortios', 'Fortinet FortiOS'), ('panos', 'Palo Alto PAN-OS'), ('sonicwall', 'SonicWall SonicOS'), ('aos_cx', 'HPE AOS-CX'), ('aruba', 'Aruba AOS'), ('sonic', 'SONiC'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
