# Generated by Django 6.0.5 on 2026-06-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_alter_device_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovereddevice',
            name='device_category',
            field=models.CharField(choices=[('network_device', 'Network Device'), ('endpoint', 'Endpoint/Workstation'), ('server', 'Server'), ('printer', 'Printer'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='discovereddevice',
            name='os_accuracy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discovereddevice',
            name='os_detected',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
