# Generated by Django 6.0.5 on 2026-06-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_discovereddevice_device_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoveryjob',
            name='method',
            field=models.CharField(choices=[('ping_snmp', 'Ping + SNMP (production-safe)'), ('topology', 'Topology Walk (CDP/LLDP/route table)'), ('passive', 'Passive (ingest source IPs)'), ('scan', 'Active Scan (SNMP/SSH probe)'), ('ping', 'Ping Only (no fingerprinting)'), ('import', 'Import (NetBox/CSV)')], db_index=True, max_length=20),
        ),
    ]
