# Generated by Django 6.0.5 on 2026-06-04 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_alter_discoveryjob_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveryjob',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_jobs', to='devices.site'),
        ),
    ]
