# Generated by Django 6.0.6 on 2026-06-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_hostnamerule'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hostname_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
