# Generated by Django 6.0.6 on 2026-06-08 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0023_alter_device_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLDPNeighbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_interface', models.CharField(max_length=255)),
                ('chassis_id', models.CharField(blank=True, max_length=255)),
                ('chassis_id_type', models.CharField(blank=True, max_length=32)),
                ('port_id', models.CharField(blank=True, max_length=255)),
                ('port_description', models.CharField(blank=True, max_length=255)),
                ('system_name', models.CharField(blank=True, max_length=255)),
                ('system_description', models.TextField(blank=True)),
                ('management_address', models.GenericIPAddressField(blank=True, null=True)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('matched_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lldp_seen_as_neighbor', to='devices.device')),
                ('seen_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lldp_neighbors', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['seen_by'], name='devices_lld_seen_by_860357_idx'), models.Index(fields=['matched_device'], name='devices_lld_matched_40c5f8_idx')],
                'constraints': [models.UniqueConstraint(fields=('seen_by', 'local_interface'), name='unique_lldp_neighbor_per_port')],
            },
        ),
    ]
