# Generated by Django 6.0.6 on 2026-06-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0027_device_ip_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='platform',
            field=models.CharField(choices=[('ios', 'Cisco IOS'), ('ios_xe', 'Cisco IOS-XE'), ('ios_xr', 'Cisco IOS-XR'), ('nxos', 'Cisco NX-OS'), ('eos', 'Arista EOS'), ('junos', 'Juniper JunOS'), ('fortios', 'Fortinet FortiOS'), ('panos', 'Palo Alto PAN-OS'), ('sonicwall', 'SonicWall SonicOS'), ('aos_cx', 'HPE AOS-CX'), ('aruba', 'Aruba AOS'), ('sonic', 'SONiC'), ('unifi_ap', 'UniFi Access Point'), ('unifi_sw', 'UniFi Switch'), ('unifi_gw', 'UniFi Gateway'), ('unifi_udm', 'UniFi Dream Machine'), ('unifi_uckp', 'UniFi CloudKey'), ('unifi_ucg', 'UniFi Console Gateway'), ('mist_ap', 'Mist Access Point'), ('mist_sw', 'Mist Switch'), ('mist_gw', 'Mist Gateway'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
