# Generated by Django 6.0.6 on 2026-06-20 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0029_normalize_lldp_capabilities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTopologyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interface_a', models.CharField(blank=True, max_length=64)),
                ('interface_b', models.CharField(blank=True, max_length=64)),
                ('link_type', models.CharField(choices=[('ethernet', 'Ethernet'), ('fiber', 'Fiber'), ('wan', 'WAN Circuit'), ('lacp', 'LACP/LAG'), ('mgmt', 'Management'), ('virtual', 'Virtual/Tunnel'), ('other', 'Other')], default='ethernet', max_length=20)),
                ('speed_mbps', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_links_created', to=settings.AUTH_USER_MODEL)),
                ('device_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_links_a', to='devices.device')),
                ('device_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_links_b', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['device_a'], name='devices_man_device__0cf102_idx'), models.Index(fields=['device_b'], name='devices_man_device__17a40e_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_a', 'interface_a', 'device_b', 'interface_b'), name='unique_manual_topology_link')],
            },
        ),
    ]
