# Generated by Django 6.0.6 on 2026-06-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    """Schema-only: add the device_kind column + its index. The one-time backfill
    is a SEPARATE migration (0032) on purpose — Django defers index creation
    (db_index=True) to the end of a migration's schema_editor, so running the
    backfill UPDATEs in the SAME migration leaves pending deferred FK-trigger
    events and Postgres then refuses `CREATE INDEX ... has pending trigger
    events`. (SQLite has no such constraint, so the SQLite test suite didn't
    catch it.) Keeping this migration pure schema lets the index build cleanly."""

    dependencies = [
        ('devices', '0030_manualtopologylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_kind',
            field=models.CharField(choices=[('network_device', 'Network Device'), ('server', 'Server')], db_index=True, default='network_device', max_length=20),
        ),
    ]
