# Generated by Django 6.0.5 on 2026-05-29 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceresult',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_results', to='devices.device'),
        ),
        migrations.AddField(
            model_name='complianceresult',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='compliance.compliancepolicy'),
        ),
        migrations.AddField(
            model_name='complianceresult',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='compliance.compliancepolicyrule'),
        ),
        migrations.AddIndex(
            model_name='complianceresult',
            index=models.Index(fields=['device', 'policy', '-created_at'], name='compliance__device__e1cb3a_idx'),
        ),
    ]
