# Generated by Django 6.0.6 on 2026-06-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_compliancetemplate_devicecomplianceoverride_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedOSVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='e.g. ios_xe, aos_cx, fortios', max_length=64)),
                ('version_pattern', models.CharField(help_text='Exact version or regex pattern. e.g. "17.12.*" or "10.13.1000"', max_length=128)),
                ('is_regex', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('preferred', 'Preferred'), ('deprecated', 'Deprecated - Update Soon'), ('prohibited', 'Prohibited - Update Now')], default='approved', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['platform', 'version_pattern'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredPlatformModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=64)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('os_version', models.CharField(blank=True, max_length=128)),
                ('device_count', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('os_status', models.CharField(choices=[('approved', 'Approved'), ('preferred', 'Preferred'), ('deprecated', 'Deprecated'), ('prohibited', 'Prohibited'), ('unknown', 'Not in policy')], default='unknown', max_length=20)),
            ],
            options={
                'ordering': ['platform', 'model'],
                'unique_together': {('platform', 'model', 'os_version')},
            },
        ),
    ]
