# Generated by Django 6.0.6 on 2026-06-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_approvedosversion_discoveredplatformmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedosversion',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('preferred', 'Preferred'), ('deprecated', 'Deprecated - Update Soon'), ('prohibited', 'Prohibited - Update Now'), ('unknown', 'Unset - Needs Review')], default='approved', max_length=20),
        ),
    ]
