# Generated by Django 6.0.6 on 2026-06-13 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_alter_approvedosversion_status'),
        ('devices', '0028_alter_device_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('trigger', models.CharField(choices=[('lldp_capability', 'LLDP Neighbor Capability'), ('lldp_neighbor_platform', 'LLDP Neighbor Platform'), ('lldp_neighbor_role', 'LLDP Neighbor Role'), ('interface_description', 'Interface Description Pattern'), ('manual', 'Manual Interface Tag')], default='lldp_capability', max_length=32)),
                ('trigger_value', models.CharField(help_text='lldp_capability: capability name (wlan-access-point, telephone, bridge, router, station). lldp_neighbor_platform: comma-separated platforms. interface_description: regex. manual: comma-separated hostname:interface.', max_length=256)),
                ('platform', models.CharField(blank=True, help_text='Switch platform filter, e.g. aos_cx', max_length=64)),
                ('checks', models.JSONField(default=list, help_text='List of config checks')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoleConsistencyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('check_type', models.CharField(choices=[('vlan_consistency', 'VLAN Consistency'), ('ntp_consistency', 'NTP Server Consistency'), ('dns_consistency', 'DNS Server Consistency'), ('banner_consistency', 'Login Banner Consistency'), ('snmp_consistency', 'SNMP Community Consistency'), ('aaa_consistency', 'AAA/RADIUS Consistency')], default='vlan_consistency', max_length=32)),
                ('platform', models.CharField(blank=True, help_text='Limit to this platform', max_length=64)),
                ('excluded_vlans', models.JSONField(default=list, help_text='VLAN IDs to exclude from comparison, e.g. [1, 999]')),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_summary', models.JSONField(blank=True, default=dict)),
                ('role', models.ForeignKey(blank=True, help_text='Compare devices with this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consistency_rules', to='devices.devicerole')),
                ('site', models.ForeignKey(blank=True, help_text='Limit to this site (blank = all)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consistency_rules', to='devices.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InterfaceComplianceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interface', models.CharField(max_length=255)),
                ('neighbor', models.CharField(blank=True, max_length=255)),
                ('trigger_match', models.CharField(blank=True, max_length=128)),
                ('passed', models.BooleanField(default=True)),
                ('findings', models.JSONField(default=list)),
                ('checks_total', models.IntegerField(default=0)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_compliance_results', to='devices.device')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='compliance.interfacecompliancerule')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['device', 'rule'], name='compliance__device__ba2158_idx')],
                'constraints': [models.UniqueConstraint(fields=('rule', 'device', 'interface'), name='uniq_iface_compliance_result')],
            },
        ),
    ]
