# Generated by Django 6.0.6 on 2026-06-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0007_interface_rule_compound_capabilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacecompliancerule',
            name='trigger',
            field=models.CharField(choices=[('lldp_capability', 'LLDP Neighbor Capability'), ('lldp_neighbor_platform', 'LLDP Neighbor Platform'), ('lldp_neighbor_role', 'LLDP Neighbor Role'), ('interface_name', 'Interface Name Pattern'), ('interface_description', 'Interface Description Pattern'), ('manual', 'Manual Interface Tag')], default='lldp_capability', max_length=32),
        ),
    ]
