# Generated by Django 6.0.6 on 2026-06-20 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0008_alter_interfacecompliancerule_trigger'),
        ('devices', '0029_normalize_lldp_capabilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceComplianceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(blank=True, help_text='0.0-100.0 weighted %', null=True)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('template_score', models.FloatField(blank=True, null=True)),
                ('interface_score', models.FloatField(blank=True, null=True)),
                ('role_score', models.FloatField(blank=True, null=True)),
                ('startup_match', models.BooleanField(null=True)),
                ('checked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_summary', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
