# Generated by Django 6.0.6 on 2026-06-20 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0030_manualtopologylink'),
    ]

    operations = [
        migrations.CreateModel(
            name='WanCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. "WCO2 Primary Internet"', max_length=128)),
                ('circuit_id', models.CharField(blank=True, help_text='Provider circuit ID', max_length=128)),
                ('circuit_type', models.CharField(choices=[('mpls', 'MPLS'), ('internet', 'Internet'), ('dia', 'Dedicated Internet Access'), ('broadband', 'Broadband'), ('fiber', 'Fiber'), ('coax', 'Coax/Cable'), ('lte', 'LTE/Cellular'), ('sdwan', 'SD-WAN'), ('dark_fiber', 'Dark Fiber'), ('p2p', 'Point-to-Point'), ('other', 'Other')], default='internet', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Install'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('provider', models.CharField(blank=True, help_text='e.g. AT&T, Comcast, Lumen', max_length=128)),
                ('provider_account', models.CharField(blank=True, max_length=128)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('monthly_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bandwidth_mbps_download', models.IntegerField(blank=True, help_text='Download/ingress Mbps', null=True)),
                ('bandwidth_mbps_upload', models.IntegerField(blank=True, help_text='Upload/egress Mbps. Blank = same as download', null=True)),
                ('committed_mbps', models.IntegerField(blank=True, help_text='CIR - Committed Information Rate', null=True)),
                ('isp_ipv4_block', models.CharField(blank=True, help_text='e.g. 203.0.113.0/30', max_length=64)),
                ('isp_ipv6_block', models.CharField(blank=True, help_text='e.g. 2001:db8::/48', max_length=128)),
                ('gateway_ip', models.GenericIPAddressField(blank=True, help_text='ISP gateway/next-hop IP', null=True)),
                ('usable_ips', models.CharField(blank=True, help_text='e.g. 203.0.113.1 - 203.0.113.2', max_length=128)),
                ('bgp_asn', models.CharField(blank=True, help_text='ISP BGP ASN if applicable', max_length=20)),
                ('our_bgp_asn', models.CharField(blank=True, help_text='Our BGP ASN if applicable', max_length=20)),
                ('interface', models.CharField(blank=True, help_text='Interface name, e.g. GigabitEthernet0/0/1', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='WAN IP on this circuit', null=True)),
                ('alert_threshold_pct', models.IntegerField(default=80, help_text='Alert when utilization exceeds this %')),
                ('notes', models.TextField(blank=True)),
                ('device', models.ForeignKey(blank=True, help_text='Router/firewall this circuit terminates on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wan_circuits', to='devices.device')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wan_circuits', to='devices.site')),
            ],
            options={
                'ordering': ['site__name', 'name'],
            },
        ),
    ]
