# Generated by Django 6.0.5 on 2026-05-29 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cve_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], db_index=True, max_length=10)),
                ('cvss_score', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('cvss_vector', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('source_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceCVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_patched', models.BooleanField(db_index=True, default=False)),
                ('patched_at', models.DateTimeField(blank=True, null=True)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_devices', to='cve.cve')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cves', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['device', 'is_patched'], name='cve_devicec_device__146b6b_idx')],
                'unique_together': {('device', 'cve')},
            },
        ),
    ]
