# Generated by Django 6.0.5 on 2026-05-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVEFeedSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nvd_enabled', models.BooleanField(default=True)),
                ('cisa_kev_enabled', models.BooleanField(default=True)),
                ('cisco_psirt_enabled', models.BooleanField(default=False)),
                ('paloalto_enabled', models.BooleanField(default=False)),
                ('nvd_api_key_vault_path', models.CharField(blank=True, max_length=255)),
                ('cisco_psirt_client_id_vault_path', models.CharField(blank=True, max_length=255)),
                ('paloalto_api_key_vault_path', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'CVE feed settings',
                'verbose_name_plural': 'CVE feed settings',
            },
        ),
    ]
