# Generated by Django 6.0.5 on 2026-06-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve', '0002_cvefeedsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve',
            name='affected_platforms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cve',
            name='cisa_kev',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='cve',
            name='cpe_configs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cve',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cve',
            name='source',
            field=models.CharField(db_index=True, default='nvd', max_length=20),
        ),
        migrations.AddField(
            model_name='cvefeedsettings',
            name='last_sync_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cvefeedsettings',
            name='last_sync_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cvefeedsettings',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicecve',
            name='match_detail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='devicecve',
            name='match_type',
            field=models.CharField(choices=[('exact_version', 'Exact version'), ('version_range', 'Version range'), ('keyword', 'Keyword / platform'), ('unverified', 'Unverified (version unknown)')], db_index=True, default='keyword', max_length=16),
        ),
        migrations.AddField(
            model_name='devicecve',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
