# Generated by Django 6.0.6 on 2026-06-09 22:16

import apps.agents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0026_device_mac_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('role_type', models.CharField(choices=[('dhcp', 'DHCP Server'), ('dns', 'DNS Server'), ('nps', 'Network Policy Server'), ('dc', 'Domain Controller'), ('web', 'Web Server'), ('db', 'Database Server'), ('file', 'File Server'), ('print', 'Print Server'), ('syslog', 'Syslog Server'), ('monitoring', 'Monitoring Server'), ('custom', 'Custom')], db_index=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('windows_services', models.JSONField(default=list, help_text='Windows service names to monitor')),
                ('linux_services', models.JSONField(default=list, help_text='systemd unit names to monitor')),
                ('port_checks', models.JSONField(default=list, help_text='[{"port": 53, "proto": "udp", "name": "DNS"}]')),
                ('custom_checks', models.JSONField(default=list)),
                ('is_builtin', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentEnrollmentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, default=apps.agents.models._generate_token, max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.IntegerField(default=1, help_text='0 = unlimited')),
                ('use_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tokens', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tokens', to='devices.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(db_index=True, max_length=255)),
                ('os', models.CharField(blank=True, max_length=64)),
                ('arch', models.CharField(blank=True, max_length=32)),
                ('version', models.CharField(blank=True, max_length=32)),
                ('cert_serial', models.CharField(blank=True, db_index=True, max_length=128)),
                ('cert_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=20)),
                ('collection_interval', models.IntegerField(default=30, help_text='seconds')),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent', to='devices.device')),
                ('enrollment_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='agents.agentenrollmenttoken')),
                ('server_roles', models.ManyToManyField(blank=True, related_name='agents', to='agents.serverrole')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentRoleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_type', models.CharField(max_length=32)),
                ('services', models.JSONField(default=list)),
                ('ports', models.JSONField(default=list)),
                ('custom', models.JSONField(default=list)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_statuses', to='agents.agent')),
            ],
            options={
                'ordering': ['role_type'],
                'abstract': False,
                'unique_together': {('agent', 'role_type')},
            },
        ),
    ]
