# Generated by Django 6.0.6 on 2026-06-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_seed_builtin_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentenrollmenttoken',
            name='target_os',
            field=models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows'), ('any', 'Any')], default='any', max_length=20),
        ),
    ]
