# Generated by Django 6.0.6 on 2026-06-10 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agentenrollmenttoken_target_os'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='reported_services',
            field=models.JSONField(blank=True, default=list),
        ),
        # Django can't add `through=` to an existing M2M via AlterField — drop the
        # auto-created M2M, create the explicit through model, then re-add the M2M
        # pointing at it. Safe: the M2M has no data yet (new feature).
        migrations.RemoveField(
            model_name='agent',
            name='server_roles',
        ),
        migrations.CreateModel(
            name='AgentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_detected', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_roles', to='agents.agent')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_assignments', to='agents.serverrole')),
            ],
            options={
                'ordering': ['role__name'],
                'abstract': False,
                'unique_together': {('agent', 'role')},
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='server_roles',
            field=models.ManyToManyField(blank=True, related_name='agents', through='agents.AgentRole', to='agents.serverrole'),
        ),
    ]
