# Generated by Django 6.0.6 on 2026-06-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agent_cert_serial_normalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='desired_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
