# Generated by Django 6.0.6 on 2026-06-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agent_desired_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='os_kernel',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='agent',
            name='os_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='agent',
            name='os_version',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
