# Generated by Django 6.0.6 on 2026-06-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agent_os_kernel_agent_os_name_agent_os_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='liveness_alerts_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='offline_threshold_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
