# Generated by Django 6.0.6 on 2026-06-28 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agent_liveness_alerts_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('running', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, max_length=32)),
                ('last_change_at', models.DateTimeField(blank=True, null=True)),
                ('down_since', models.DateTimeField(blank=True, null=True)),
                ('restarts', models.JSONField(default=list)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_services', to='agents.agent')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('agent', 'name')},
            },
        ),
    ]
