# Generated by Django 6.0.6 on 2026-06-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_watchedservicestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrolestatus',
            name='functional',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
