# Generated by Django 6.0.6 on 2026-06-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_agentrolestatus_functional'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
